/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Format;

import java.awt.event.ItemEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ahmed.elemam
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }
    
    String H_fields;
    String R_fields;
    String F_fields;
    
    String H_length;
    String R_length;
    String F_length;
    
    String Line;
    String Spliter;
    
    String [] ALL_Line;
    String  L_header;
    ArrayList L_record = new ArrayList();
    String  L_footer;
    StringBuffer result=new StringBuffer();
    
    boolean header=false;
    boolean record=false;
    boolean footer=false;
    boolean H_sucess=false;
    boolean R_sucess=false;
    boolean F_sucess=false;
    
       JFileChooser chooser ;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Line");

        jTextField1.setEnabled(false);

        jLabel2.setText("Header Fields with comma");
        jLabel2.setEnabled(false);

        jLabel3.setText("Header Length with comma");
        jLabel3.setEnabled(false);

        jTextField2.setEnabled(false);

        jButton1.setText("Parse");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel4.setText("Records Fields with comma");
        jLabel4.setEnabled(false);

        jTextField3.setEnabled(false);

        jLabel5.setText("Records Length with comma");
        jLabel5.setEnabled(false);

        jTextField4.setEnabled(false);

        jLabel6.setText("Footer Fields with comma");
        jLabel6.setEnabled(false);

        jTextField5.setEnabled(false);

        jTextField6.setEnabled(false);

        jLabel7.setText("Footer Length with comma");
        jLabel7.setEnabled(false);

        jLabel8.setText("Pasring File");

        jButton2.setText("Export Fields");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Import Fields");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jCheckBox1.setText("Header");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });

        jCheckBox2.setText("Records");
        jCheckBox2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox2StateChanged(evt);
            }
        });

        jCheckBox3.setText("Footer");
        jCheckBox3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox3StateChanged(evt);
            }
        });

        jLabel10.setText("Split Word");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jCheckBox1)
                                .addGap(30, 30, 30)
                                .addComponent(jCheckBox2)
                                .addGap(39, 39, 39)
                                .addComponent(jCheckBox3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(12, 12, 12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addGap(34, 34, 34))))
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jButton1))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        
     Line=jTextArea1.getText();
     Spliter=jTextField8.getText().trim();
     if(Spliter == null || Spliter.equals("")){
         
          JOptionPane.showMessageDialog(this,"Please enter Split Word"); 
     result=new StringBuffer();
     }else{
  if(!header && !footer && !record){
   JOptionPane.showMessageDialog(this,"Please enter Header or Record or Footer"); 
  }else{       
         
         
     ALL_Line = Line.split(Spliter);
     
        
if(header){
         
         L_header = ALL_Line[0];
         
H_fields=jTextField1.getText().trim();
H_length=jTextField2.getText().trim();

String [] F1=H_fields.split(",");
String [] L1=H_length.split(",");



if(F1.length == L1.length){
int j=0;
int lenequal=0;

 for(int i=0;i<F1.length;i++){       
       lenequal=lenequal+Integer.parseInt(L1[i]);
    }
 
 if(lenequal==L_header.length()){
 


    for(int i=0;i<F1.length;i++){
        
        result.append("Header --> ").append(F1[i]).append(" : ").append(L_header.substring(j,j+Integer.parseInt(L1[i]))).append("\n");
       // System.out.println(F1[i] +" : "+ Line.substring(j,j+Integer.parseInt(L1[i])));
        
       //    System.out.println("V "+j +" "+i);
        
       j=j+Integer.parseInt(L1[i]);
     
    //  System.out.println("Vx "+j+" "+i);
    }

H_sucess=true;
 }else{
 JOptionPane.showMessageDialog(this,"Please Header Length of text area not match with Header length's");  
H_sucess=false;
}
 
 }else{
 JOptionPane.showMessageDialog(this,"Please enter Valid Header Fields or Length"); 
H_sucess=false; 
}

     
     }


if(footer){
         
 L_footer = ALL_Line[ALL_Line.length-1];
         
F_fields=jTextField5.getText().trim();
F_length=jTextField6.getText().trim();

String [] F1=F_fields.split(",");
String [] L1=F_length.split(",");



if(F1.length == L1.length){
int j=0;
int lenequal=0;

 for(int i=0;i<F1.length;i++){       
       lenequal=lenequal+Integer.parseInt(L1[i]);
    }
 
 if(lenequal==L_footer.length()){
 


    for(int i=0;i<F1.length;i++){
        
        result.append("Footer --> ").append(F1[i]).append(" : ").append(L_footer.substring(j,j+Integer.parseInt(L1[i]))).append("\n");
       // System.out.println(F1[i] +" : "+ Line.substring(j,j+Integer.parseInt(L1[i])));
        
       //    System.out.println("V "+j +" "+i);
        
       j=j+Integer.parseInt(L1[i]);
     
    //  System.out.println("Vx "+j+" "+i);
    }

F_sucess=true;
 }else{
 JOptionPane.showMessageDialog(this,"Please Footer Length of text area not match with Footer length's");  
F_sucess=false;
}
 
 }else{
 JOptionPane.showMessageDialog(this,"Please enter Valid Footer Fields or Length"); 
F_sucess=false; 
}

  }

if(record){
   L_record.clear();
         int j=0;
    for(int i1=0;i1<ALL_Line.length;i1++){
    
        if(header && i1==0){
         //   System.out.println("F1 "+ ALL_Line[i1]);
        
        }else if(footer && i1==ALL_Line.length-1){    
       //  System.out.println("F2 "+ ALL_Line[i1]);
        }else{
            // System.out.println("F3 "+ ALL_Line[i1]);
             L_record.add(ALL_Line[i1]);
            
        }
   
    }
    
    
    if(L_record ==null || L_record.size() == 0){
    JOptionPane.showMessageDialog(this,"No record"); 
    }else{
        
        R_fields=jTextField3.getText().trim();
R_length=jTextField4.getText().trim();

String [] F1=R_fields.split(",");
String [] L1=R_length.split(",");

  System.out.println("len "+ L_record.size());

  for(int i2=0;i2<L_record.size();i2++){   


if(F1.length == L1.length){
j=0;
int lenequal=0;

 for(int i=0;i<F1.length;i++){       
       lenequal=lenequal+Integer.parseInt(L1[i]);
    }
   // System.out.println(L_record.get(i2));
 if(lenequal==L_record.get(i2).toString().length()){
 


    for(int i=0;i<F1.length;i++){
        
        result.append("Record{").append(i2).append(") --> ").append(F1[i]).append(" : ").append(L_record.get(i2).toString().substring(j,j+Integer.parseInt(L1[i]))).append("\n");
       // System.out.println(F1[i] +" : "+ Line.substring(j,j+Integer.parseInt(L1[i])));
        
       //    System.out.println("V "+j +" "+i);
        
       j=j+Integer.parseInt(L1[i]);
     
    //  System.out.println("Vx "+j+" "+i);
    }

R_sucess=true;
 }else{
 JOptionPane.showMessageDialog(this,"Please "+i2+" record Length of text area not match with record length's");  
R_sucess=false;
}
 
 }else{
 JOptionPane.showMessageDialog(this,"Please "+i2+" enter Valid record Fields or Length"); 
R_sucess=false; 
}

  }
    }
}
     
   


if(H_sucess || F_sucess)
 JOptionPane.showMessageDialog(this,result.toString());  
    
result=new StringBuffer();


  }
     }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    
    
    
    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged

if(jCheckBox1.isSelected()) {//checkbox has been selected
  enable_header();
 }else{
disable_header();

}
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void jCheckBox2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox2StateChanged
        // TODO add your handling code here:
        
        if(jCheckBox2.isSelected()) {//checkbox has been selected
     enable_record();
 }else{
disable_record();
 
}
    }//GEN-LAST:event_jCheckBox2StateChanged

    public void enable_header(){
          jCheckBox1.setSelected(true);
          jLabel2.setEnabled(true);
        jLabel3.setEnabled(true);
        jTextField1.setEnabled(true);
        jTextField2.setEnabled(true);
        header=true;
    
    }
    
    public void disable_header(){
     jLabel2.setEnabled(false);
        jLabel3.setEnabled(false);
        jTextField1.setEnabled(false);
        jTextField2.setEnabled(false);
         header=false;
    
    }
    
      public void enable_record(){
            jCheckBox2.setSelected(true);
       jLabel4.setEnabled(true);
        jLabel5.setEnabled(true);
//         jLabel9.setEnabled(true);
         
        jTextField3.setEnabled(true);
        jTextField4.setEnabled(true);
      //   jTextField7.setEnabled(true);
         
         
          record=true;
    
    }
    
    public void disable_record(){
    jLabel4.setEnabled(false);
        jLabel5.setEnabled(false);
//        jLabel9.setEnabled(false);
        
        jTextField3.setEnabled(false);
        jTextField4.setEnabled(false);
    //    jTextField7.setEnabled(false);
         record=false;
    
    }
    
      public void enable_footer(){
    jCheckBox3.setSelected(true);
       jLabel6.setEnabled(true);
        jLabel7.setEnabled(true);
        jTextField5.setEnabled(true);
        jTextField6.setEnabled(true);
         footer=true;
    }
    
    public void disable_footer(){
    
     jLabel6.setEnabled(false);
        jLabel7.setEnabled(false);
        jTextField5.setEnabled(false);
        jTextField6.setEnabled(false);
         footer=false;
    }
    
    private void jCheckBox3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox3StateChanged
        // TODO add your handling code here:
          if(jCheckBox3.isSelected()) {//checkbox has been selected
     enable_footer();
 }else{
disable_footer();

}
        
    }//GEN-LAST:event_jCheckBox3StateChanged

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

        try {
            String h_f=jTextField1.getText();
            String h_l=jTextField2.getText();
            
            String r_f=jTextField3.getText();
            String r_l=jTextField4.getText();
            
            String f_f=jTextField5.getText();
            String f_l=jTextField6.getText();
            
            String spl=jTextField8.getText();
            
            
            result =new StringBuffer();
            if(header)
                result.append("H,,").append(h_f).append(",,").append(h_l).append("\n");
            if(record)
                result.append("R,,").append(r_f).append(",,").append(r_l).append("\n");
            if(footer)
                result.append("F,,").append(f_f).append(",,").append(f_l).append("\n");
            
            result.append("S,,"+spl);
            
            
           chooser   = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Pa", "pa");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showSaveDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            System.out.println("You chose to open this file: " +
                    chooser.getSelectedFile().getAbsolutePath());      
              BufferedWriter writer = new BufferedWriter(new FileWriter(chooser.getSelectedFile().getAbsolutePath()+".pa"));
            writer.write(result.toString());
            writer.close();
        }else{
         JOptionPane.showMessageDialog(this,"Please enter file"); 
        
        }
            
          
            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked

 chooser   = new JFileChooser();
 

        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                 "Pa", "pa");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            System.out.println("You chose to open this file: " +
                    chooser.getSelectedFile().getAbsolutePath());    
            
            
                    // The name of the file to open.
        String fileName =  chooser.getSelectedFile().getAbsolutePath();

        // This will reference one line at a time
        String linew = null;

        try {
            // FileReader reads text files in the default encoding.
            FileReader fileReader = 
                new FileReader(fileName);

            // Always wrap FileReader in BufferedReader.
            BufferedReader bufferedReader = 
                new BufferedReader(fileReader);

            while((linew = bufferedReader.readLine()) != null) {
                
                if(linew.startsWith("H")){
                enable_header();
                String [] h_stream=linew.split(",,");
                jTextField1.setText(h_stream[1]);
                 jTextField2.setText(h_stream[2]);
                }else if(linew.startsWith("R")){
                enable_record();
                  String [] r_stream=linew.split(",,");
                jTextField3.setText(r_stream[1]);
                 jTextField4.setText(r_stream[2]);
                }else if(linew.startsWith("F")){
                 enable_footer();
                   String [] f_stream=linew.split(",,");
                jTextField5.setText(f_stream[1]);
                 jTextField6.setText(f_stream[2]);
                }else if(linew.startsWith("S")){
                      String [] s_stream=linew.split(",,");
                jTextField8.setText(s_stream[1]);
                }else{
                
                }
                System.out.println(linew);
            }   

            // Always close files.
            bufferedReader.close();         
        }
        catch(FileNotFoundException ex) {
            System.out.println(
                "Unable to open file '" + 
                fileName + "'");                
        }
        catch(IOException ex) {
            System.out.println(
                "Error reading file '" 
                + fileName + "'");                  
            // Or we could just do this: 
            // ex.printStackTrace();
        }
    
         
        }else{
         JOptionPane.showMessageDialog(this,"Please enter file"); 
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
